!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: Pixel 5
  udid: emulator-5554
  app: F:\\apk\\app-debug_v.1.0.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true